# Generated by Django 3.2.9 on 2022-05-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220520_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='Usuario_id',
        ),
        migrations.AddField(
            model_name='documento',
            name='Usuario_id',
            field=models.ManyToManyField(to='usuario.Usuario'),
        ),
    ]
