# Generated by Django 3.2.9 on 2022-05-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20220521_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
