# Generated by Django 3.2.9 on 2022-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_documento_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
