# Generated by Django 3.2.9 on 2022-05-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='name'),
        ),
    ]
