# Generated by Django 3.2.9 on 2022-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20220530_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='archivos/'),
        ),
    ]
