# Generated by Django 3.2.9 on 2022-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_producto',
            field=models.IntegerField(choices=[(1, 'Tesis'), (2, 'Articulo'), (3, 'Monografia')], default=1),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_publicacion',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='palabras_clave',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resumen',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
